"""database fix

Revision ID: 256cd472d8fc
Revises: c678119403ac
Create Date: 2022-05-28 09:47:10.735446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '256cd472d8fc'
down_revision = 'c678119403ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('house_number', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_id'), 'delivery', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', mssql.MONEY(), nullable=True),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('telegram_login', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index('ix_Users_id', table_name='Users')
    op.drop_table('Users')
    op.drop_index('ix_Products_id', table_name='Products')
    op.drop_table('Products')
    op.drop_index('ix_Delivery_id', table_name='Delivery')
    op.drop_table('Delivery')
    op.drop_index('ix_Sales_id', table_name='Sales')
    op.drop_table('Sales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sales',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Sales_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Sales_pkey')
    )
    op.create_index('ix_Sales_id', 'Sales', ['id'], unique=False)
    op.create_table('Delivery',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Delivery_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('house_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Delivery_pkey')
    )
    op.create_index('ix_Delivery_id', 'Delivery', ['id'], unique=False)
    op.create_table('Products',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Products_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.MONEY(), autoincrement=False, nullable=True),
    sa.Column('available', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Products_pkey')
    )
    op.create_index('ix_Products_id', 'Products', ['id'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('telegram_login', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Users_pkey')
    )
    op.create_index('ix_Users_id', 'Users', ['id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_delivery_id'), table_name='delivery')
    op.drop_table('delivery')
    # ### end Alembic commands ###
