"""database fix3

Revision ID: 7dd279e37fe9
Revises: 256cd472d8fc
Create Date: 2022-05-28 13:45:16.816298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd279e37fe9'
down_revision = '256cd472d8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('sale_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'delivery', 'sales', ['sale_id'], ['id'])
    op.add_column('products', sa.Column('catalog_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'catalogs', ['catalog_id'], ['id'])
    op.add_column('sales', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'users', ['buyer_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'product_id')
    op.drop_column('sales', 'buyer_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'catalog_id')
    op.drop_constraint(None, 'delivery', type_='foreignkey')
    op.drop_column('delivery', 'sale_id')
    # ### end Alembic commands ###
